server:
  port: 8080

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler_member
    username: root
    password: 8271
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
